import type { Metadata } from "next";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ChatButton from "./components/ChatButton";
import "./globals.css";
import { lawFont } from "./fonts";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lawFont.variable} antialiased flex flex-col min-h-screen`}
      >
         <Header />
        <main className="flex-grow">{children}</main>
        <ChatButton />
        <Footer />
      </body>
    </html>
  );
}
